---

##########
# DRIVERS #
##########

# NVIDIA GPU DRIVERS
- name: Add graphics drivers PPA
  ansible.builtin.apt_repository:
    repo: ppa:graphics-drivers/ppa
    state: present
    update_cache: true
  become: true

- name: Get available NVIDIA driver packages
  ansible.builtin.shell: |
    set -o pipefail
    apt-cache search '^nvidia-driver-[0-9]+$' | grep -o 'nvidia-driver-[0-9]\+' | sort -V | tail -1
  register: latest_nvidia_driver
  changed_when: false
  become: true
  args:
    executable: /bin/bash

- name: Display latest NVIDIA driver found
  ansible.builtin.debug:
    msg: "Latest NVIDIA driver found: {{ latest_nvidia_driver.stdout }}"
  when: latest_nvidia_driver.stdout is defined

- name: Install latest NVIDIA driver
  ansible.builtin.apt:
    name: "{{ latest_nvidia_driver.stdout }}"
    state: present
    update_cache: true
  become: true
  when:
    - latest_nvidia_driver.stdout is defined
    - latest_nvidia_driver.stdout != ""
