---

##########
# DRIVERS #
##########

# NVIDIA GPU DRIVERS
- name: Download graphics drivers PPA GPG key
  ansible.builtin.get_url:
    url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xFCAE110B1118213C"
    dest: "/usr/share/keyrings/graphics-drivers-ppa.asc"
    mode: "0644"
  become: true

- name: Convert graphics drivers key to GPG keyring
  ansible.builtin.command:
    cmd: >
      gpg --batch --dearmor --yes
      --output /usr/share/keyrings/graphics-drivers-ppa.gpg
      /usr/share/keyrings/graphics-drivers-ppa.asc
  args:
    creates: "/usr/share/keyrings/graphics-drivers-ppa.gpg"
  become: true

- name: Remove temporary ASCII key file
  ansible.builtin.file:
    path: "/usr/share/keyrings/graphics-drivers-ppa.asc"
    state: absent
  become: true

- name: Add graphics drivers PPA repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/graphics-drivers-ppa.gpg] https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu {{ common.linux_mint_to_ubuntu_codename }} main"
    state: present
    filename: graphics-drivers-ppa
    update_cache: true
  become: true

- name: Get available NVIDIA driver packages
  ansible.builtin.shell: |
    set -o pipefail
    apt-cache search '^nvidia-driver-[0-9]+$' | grep -o 'nvidia-driver-[0-9]\+' | sort -V | tail -1
  register: latest_nvidia_driver
  changed_when: false
  become: true
  args:
    executable: /bin/bash

- name: Display latest NVIDIA driver found
  ansible.builtin.debug:
    msg: "Latest NVIDIA driver found: {{ latest_nvidia_driver.stdout }}"
  when: latest_nvidia_driver.stdout is defined

- name: Install latest NVIDIA driver
  ansible.builtin.apt:
    name: "{{ latest_nvidia_driver.stdout }}"
    state: present
    update_cache: true
  become: true
  when:
    - latest_nvidia_driver.stdout is defined
    - latest_nvidia_driver.stdout != ""
