---
- name: Remove old source list (underscore) for {{ repo.id }}
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/{{ repo.id }}.list"
    state: absent

- name: Remove old source list (hyphen) for {{ repo.id }}
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/{{ repo.id | replace('_', '-') }}.list"
    state: absent

- name: Download public key for {{ repo.id }}
  ansible.builtin.get_url:
    url: "{{ repo.key_url }}"
    dest: "{{ repo.ascii_key }}"
    mode: "0644"

- name: Remove any existing conflicting keyring for {{ repo.id }}
  ansible.builtin.file:
    path: "{{ repo.keyring }}"
    state: absent
  when: not ansible_check_mode

- name: Remove legacy Microsoft keyring (if exists)
  ansible.builtin.file:
    path: "/usr/share/keyrings/microsoft.gpg"
    state: absent
  when: repo.id is defined and repo.id == "vscode" and not ansible_check_mode

- name: Convert ASCII key to GPG keyring for {{ repo.id }}
  ansible.builtin.command:
    cmd: >
      gpg --batch --dearmor --yes
      --output {{ repo.keyring }}
      {{ repo.ascii_key }}
  args:
    creates: "{{ repo.keyring }}"

- name: Remove temporary ASCII key file for {{ repo.id }}
  ansible.builtin.file:
    path: "{{ repo.ascii_key }}"
    state: absent

- name: Remove any conflicting APT sources for {{ repo.id }}
  ansible.builtin.shell: |
    set -o pipefail
    find /etc/apt/sources.list.d/ -name "*.list" -exec grep -l "{{ repo.repo }}" {} \; | xargs rm -f
  args:
    executable: /bin/bash
    warn: false
  changed_when: false
  failed_when: false

- name: Remove legacy Microsoft sources (if exists)
  ansible.builtin.file:
    path: "{{ source_file }}"
    state: absent
  loop:
    - "/etc/apt/sources.list.d/vscode.list"
    - "/etc/apt/sources.list.d/microsoft-prod.list"
  loop_control:
    loop_var: source_file
  when: repo.id is defined and repo.id == "vscode"

- name: Add APT repository for {{ repo.id }}
  ansible.builtin.apt_repository:
    repo: >-
      deb [
        {{ repo.arch is defined and ("arch="~repo.arch) or "" }}
        signed-by={{ repo.keyring }}
      ]
      {{ repo.repo }}
      {{ repo.codename | default("") }}
      {{ repo.components }}
    filename: "{{ repo.id | replace('_', '-') }}"
    state: present
    update_cache: false
