---

#########
# JAVA  #
#########

# SDKMAN
- name: Check if SDKMAN is already installed
  ansible.builtin.stat:
    path: "{{ sdkman.install_dir }}"
  register: sdkman_dir

- name: Install SDKMAN
  ansible.builtin.shell: |
    set -o pipefail
    export ZDOTDIR="{{ common.dotfile_config_home }}/zsh"
    curl -s "{{ sdkman.install_url }}" | bash
  args:
    executable: /bin/bash
  when: not sdkman_dir.stat.exists
  changed_when: "true"

- name: Verify SDKMAN installation
  ansible.builtin.shell: |
    set -o pipefail
    source "{{ sdkman.init_script }}" && sdk version
  args:
    executable: /bin/bash
  register: sdkman_version
  changed_when: "false"
  failed_when: sdkman_version.rc != 0

- name: Display SDKMAN version
  ansible.builtin.debug:
    msg: "SDKMAN installed successfully: {{ sdkman_version.stdout }}"
  when: sdkman_version.stdout is defined

# SDKS
- name: Set SDKMAN to non-interactive mode
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.sdkman/etc/config"
    regexp: '^sdkman_auto_answer='
    line: 'sdkman_auto_answer=true'
    backup: true

- name: Install Java via SDKMAN
  ansible.builtin.shell: |
    set -o pipefail
    source "{{ sdkman.init_script }}" && sdk install java
  args:
    executable: /bin/bash
  register: java_install
  changed_when: "'already installed' not in java_install.stdout"

- name: Install Maven via SDKMAN
  ansible.builtin.shell: |
    set -o pipefail
    source "{{ sdkman.init_script }}" && sdk install maven
  args:
    executable: /bin/bash
  register: maven_install
  changed_when: "'already installed' not in maven_install.stdout"

- name: Install Gradle via SDKMAN
  ansible.builtin.shell: |
    set -o pipefail
    source "{{ sdkman.init_script }}" && sdk install gradle
  args:
    executable: /bin/bash
  register: gradle_install
  changed_when: "'already installed' not in gradle_install.stdout"

- name: Restore SDKMAN to interactive mode
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.sdkman/etc/config"
    regexp: '^sdkman_auto_answer='
    line: 'sdkman_auto_answer=false'

###########
# NODE JS #
###########

# FNM
- name: Check if fnm is already installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.local/share/fnm"
  register: fnm_dir

- name: Install fnm
  ansible.builtin.shell: |
    set -o pipefail
    export ZDOTDIR="{{ common.dotfile_config_home }}/zsh"
    curl -fsSL https://fnm.vercel.app/install | bash
  args:
    executable: /bin/bash
  when: not fnm_dir.stat.exists
  changed_when: "true"

- name: Configure fnm with auto-use and recursive version file strategy
  ansible.builtin.replace:
    path: "{{ common.dotfile_config_home }}/zsh/.zshrc"
    regexp: 'eval "`fnm env`"'
    replace: 'eval "$(fnm env --use-on-cd --version-file-strategy=recursive)"'
  when: not fnm_dir.stat.exists

# SDKS
- name: Install Node.js LTS via fnm
  ansible.builtin.shell: |
    set -o pipefail
    export PATH="{{ ansible_env.HOME }}/.local/share/fnm:$PATH"
    eval "$(fnm env)"
    fnm install --lts
  args:
    executable: /bin/bash
  register: node_install
  changed_when: "'already installed' not in node_install.stdout"
