---

- name: Bootstrap local developer machine
  hosts: local
  gather_facts: true
  pre_tasks:
    - name: Update repositories and perform dist-upgrade on Debian/Ubuntu
      when: ansible_facts.pkg_mgr == 'apt'
      become: true
      ansible.builtin.apt:
        update_cache: true  # runs apt-get update
        upgrade: dist # runs apt-get dist-upgrade

    - name: Sync database and upgrade on Arch Linux
      when: ansible_facts.pkg_mgr == 'pacman'
      become: true
      community.general.pacman:
        update_cache: true  # runs pacman -Sy
        upgrade: true # runs pacman -Su

  # Should be run in order below
  roles:
    - role: zsh-install
      become: true
    - role: zsh-dotfiles
    - role: zsh-p10k

  post_tasks:
    - name: Notify user to re-login for shell change to take effect
      ansible.builtin.debug:
        msg: "Bootstrap complete! Please log out and log back in"
