---

- name: Bootstrap local developer machine
  hosts: local
  gather_facts: true
  # Should be run in order below
  roles:
    - update
    - zsh-install
    - zsh-dotfiles
    - zsh-themes
    - zsh_plugins
    - packages
    - programs
    - programming_languages
    - docker
    - drivers

  post_tasks:
    - name: Notify user to re-login for shell change to take effect
      ansible.builtin.debug:
        msg: "Bootstrap complete! Please reboot the system"
