---

- name: Bootstrap local developer machine
  hosts: local
  gather_facts: true
  # Should be run in order below
  roles:
    - role: update

    - role: zsh-install
      become: true

    - role: zsh-dotfiles

    - role: zsh-themes

    - role: zsh_plugins

  post_tasks:
    - name: Notify user to re-login for shell change to take effect
      ansible.builtin.debug:
        msg: "Bootstrap complete! Please log out and log back in"
