---

- name: Determine OS-specific update file
  ansible.builtin.include_role:
    name: helper_os_task_locator
  vars:
    my_role_name: update

- name: Include OS-specific update tasks
  ansible.builtin.include_tasks:
    file: "{{ os_specific_file }}"
    apply:
      become: true
