---

- name: Determine OS-specific update file
  ansible.builtin.include_role:
    name: helper_os_task_locator
  vars:
    base_role_path: "{{ playbook_dir }}/roles/update"
    include_dir: systems

- name: Include OS-specific update tasks
  ansible.builtin.include_tasks:
    file: "{{ os_specific_file }}"
    apply:
      become: true
