---

- name: Sync database and upgrade on Arch Linux
  when: ansible_facts.pkg_mgr == 'pacman'
#  become: true
  community.general.pacman:
    update_cache: true  # runs pacman -Sy
    upgrade: true # runs pacman -Su
