---

- name: Ensure font directory exists
  ansible.builtin.file:
    path: "{{ font.dir }}"
    state: directory
    mode: '0755'

- name: Download Powerlevel10k fonts
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ font.dir }}/{{ item.name }}"
    mode: '0644'
  loop: "{{ font.download_list }}"

- name: Print IntelliJ font setup instructions
  ansible.builtin.debug:
    msg: "{{ font.install_msg_IntelliJ }}"

- name: Clone Powerlevel10k repository
  ansible.builtin.git:
    repo: "{{ p10k_repository.url }}"
    dest: "{{ p10k_repository.dest }}"
    version: "{{ p10k_repository.version }}"
    depth: 1
    update: true

# 1) Gather possible OS-specific files
- name: Find OS-specific font setup file(s)
  ansible.builtin.set_fact:
    font_setup_files: >-
      {{
        lookup('fileglob',
               role_path + '/tasks/font_setup/' + ansible_facts['distribution'] + '.yml',
               wantlist=True)
        +
        lookup('fileglob',
               role_path + '/tasks/font_setup/' + ansible_facts['os_family'] + '.yml',
               wantlist=True)
      }}

# 2) Fail early if none found, with a descriptive error
- name: Fail if no OS-specific font setup file is present
  ansible.builtin.fail:
    msg: |
      No OS-specific font_setup file found for your platform.
      Distribution: {{ ansible_facts['distribution'] }}
      OS family:   {{ ansible_facts['os_family'] }}
      Paths tried:
        - {{ role_path }}/tasks/font_setup/{{ ansible_facts['distribution'] }}.yml
        - {{ role_path }}/tasks/font_setup/{{ ansible_facts['os_family'] }}.yml
  when: font_setup_files | length == 0

# 3) Include the first matching file
- name: Include OS-specific font setup tasks
  ansible.builtin.include_tasks: "{{ font_setup_files[0] }}"
