---

- name: Ensure font directory exists
  ansible.builtin.file:
    path: "{{ font.dir }}"
    state: directory
    mode: '0755'

- name: Download Powerlevel10k fonts
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ font.dir }}/{{ item.name }}"
    mode: '0644'
  loop: "{{ font.download_list }}"

- name: Print IntelliJ font setup instructions
  ansible.builtin.debug:
    msg: "{{ font.install_msg_IntelliJ }}"

- name: Clone Powerlevel10k repository
  ansible.builtin.git:
    repo: "{{ p10k_repository.url }}"
    dest: "{{ p10k_repository.dest }}"
    version: "{{ p10k_repository.version }}"
    depth: 1
    update: true

# You can add a file named <Distribution>.yml (e.g. Ubuntu.yml, Fedora.yml)
# or <OS_Family>.yml (e.g., Debian.yml, RedHat.yml) under tasks/font_setup/,
# and the first match will be included below.
- name: Find OS-specific font setup file(s)
  # Build a list of candidate files by globbing for both exact distro and family
  ansible.builtin.set_fact:
    font_setup_files: >-
      {{
        lookup('fileglob',
               role_path + '/tasks/font_setup/' + ansible_facts['distribution'] + '.yml',
               wantlist=True)
        +
        lookup('fileglob',
               role_path + '/tasks/font_setup/' + ansible_facts['os_family'] + '.yml',
               wantlist=True)
      }}

- name: Fail if no OS-specific font setup file is present
  # If neither a distro-specific nor family-specific file was found, abort with a clear error.
  ansible.builtin.fail:
    msg: |
      No OS-specific font_setup file found for your platform.
      Distribution: {{ ansible_facts['distribution'] }}
      OS family:   {{ ansible_facts['os_family'] }}
      Paths tried:
        - {{ role_path }}/tasks/font_setup/{{ ansible_facts['distribution'] }}.yml
        - {{ role_path }}/tasks/font_setup/{{ ansible_facts['os_family'] }}.yml
  when: font_setup_files | length == 0

- name: Include OS-specific font setup tasks
  # Load the first matching file (distro first, then family)
  ansible.builtin.include_tasks: "{{ font_setup_files[0] }}"
