---

- name: Install common essential programs on Arch Linux
  ansible.builtin.pacman:
    name: "{{ essential_programs.common + essential_programs.arch.official }}"
    state: present
    update_cache: true
  become: true

- name: Ensure AUR helper is installed
  ansible.builtin.pacman:
    name: yay
    state: present
  become: true

- name: Install AUR packages for Arch Linux
  community.general.aur:
    name: "{{ essential_programs.arch.aur }}"
    state: present
    use: yay
  become: true
