---

###################
### Custom Repo ###
###################
# Repo: Google Chrome
- name: Download Google Chrome signing key
  ansible.builtin.get_url:
    url: "{{ essential_programs.debian_repos.custom.google_chrome.key_url }}"
    dest: "{{ essential_programs.debian_repos.custom.google_chrome.keyrings }}"
    mode: '0644'
  become: true

- name: Add Google Chrome apt repository (signed-by keyring)
  ansible.builtin.apt_repository:
    repo: |
      deb [arch=amd64 signed-by={{ essential_programs.debian_repos.custom.google_chrome.keyrings }}]
      {{ essential_programs.debian_repos.custom.google_chrome.repo }}
    state: present
  become: true

# Repo: Spotify
- name: Download Spotify signing key
  ansible.builtin.get_url:
    url: "{{ essential_programs.debian_repos.custom.spotify.key_url }}"
    dest: "{{ essential_programs.debian_repos.custom.spotify.keyrings }}"
    mode: '0644'
  become: true

- name: Add Spotify apt repository (signed-by keyring)
  ansible.builtin.apt_repository:
    repo: |
      deb [signed-by={{ essential_programs.debian_repos.custom.spotify.keyrings }}]
      {{ essential_programs.debian_repos.custom.spotify.repo }}
    filename: spotify
    state: present
  become: true

# PPA Repos
- name: Add PPA repositories
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ essential_programs.debian_repos.ppa }}"
  become: true

# Update
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

###################
### Custom Apps ###
###################
- name: Install custom apps from debian repos
  ansible.builtin.apt:
    name: "{{ item.value.name }}"
    state: present
    install_recommends: true
  become: true
  loop: "{{ essential_programs.debian_repos.custom | dict2items }}"

###################
##### Flatpak #####
###################
- name: Install Flatpak apps
  community.general.flatpak:
    name: "{{ essential_programs.flatpak }}"
    state: present
    remote: flathub
    method: system
  become: true

###################
# Common Programs #
###################
- name: Install common programs on Debian-based
  ansible.builtin.apt:
    name: "{{ essential_programs.common }}"
    state: present
    install_recommends: false
  become: true
