---

###################
### Custom Repo ###
###################
# Repo: Google Chrome
- name: Download Google Chrome signing key
  ansible.builtin.get_url:
    url: "{{ essential_programs.debian_repos.custom.google_chrome.key_url }}"
    dest: "{{ essential_programs.debian_repos.custom.google_chrome.keyrings }}"
    mode: '0644'
  become: true

- name: Add Google Chrome apt repository (signed-by keyring)
  ansible.builtin.apt_repository:
    repo: |
      deb [arch=amd64 signed-by={{ essential_programs.debian_repos.custom.google_chrome.keyrings }}]
      {{ essential_programs.debian_repos.custom.google_chrome.repo }}
    state: present
  become: true

# Repo: Spotify
- name: Download Spotify signing key (ASCII)
  ansible.builtin.get_url:
    url: "{{ essential_programs.debian_repos.custom.spotify.key_url }}"
    dest: "{{ essential_programs.debian_repos.custom.spotify.keyrings }}.asc"
    mode: '0644'
  become: true

- name: Convert Spotify GPG key to binary (dearmor)
  ansible.builtin.command:
    cmd: >
      gpg --batch --dearmor
      --yes
      --output {{ essential_programs.debian_repos.custom.spotify.keyrings }}
      {{ essential_programs.debian_repos.custom.spotify.keyrings }}.asc
  args:
    creates: "{{ essential_programs.debian_repos.custom.spotify.keyrings }}"
  become: true

- name: Remove temporary ASCII Spotify key
  ansible.builtin.file:
    path: "{{ essential_programs.debian_repos.custom.spotify.keyrings }}.asc"
    state: absent
  become: true

- name: Add Spotify APT source list
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/spotify.list
    content: |
      deb {{ essential_programs.debian_repos.custom.spotify.repo }}
    mode: '0644'
  become: true

# PPA Repos
- name: Add PPA repositories
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    codename: "{{ ansible_facts.lsb.codename }}"
    update_cache: false
  loop: "{{ essential_programs.debian_repos.ppa }}"
  become: true

# Update
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

###################
### Custom Apps ###
###################
- name: Install custom apps from debian repos
  ansible.builtin.apt:
    name: "{{ item.value.name }}"
    state: present
    install_recommends: true
  become: true
  loop: "{{ essential_programs.debian_repos.custom | dict2items }}"

###################
##### Flatpak #####
###################
- name: Install Flatpak apps
  community.general.flatpak:
    name: "{{ essential_programs.flatpak }}"
    state: present
    remote: flathub
    method: system
  become: true

###################
# Common Programs #
###################
- name: Install common programs on Debian-based
  ansible.builtin.apt:
    name: "{{ essential_programs.common }}"
    state: present
    install_recommends: false
  become: true
