---

###################
### Custom Repo ###
###################
- name: Cleanup any legacy underscore-named repo lists
  become: true
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/{{ item.id }}.list"
    state: absent
  loop: "{{ essential_programs.debian_repos }}"
  loop_control:
    label: "{{ item.id }}"

# PPA Repos
- name: Determine upstream Ubuntu codename for PPAs
  ansible.builtin.set_fact:
    upstream_codename: >-
      {{ upstream_codename_map[
           (
             ansible_facts['distribution']
               | lower
               | replace(' ', '_')
           ) ~ '_' ~
           ansible_facts.lsb.major_release
         ]
         | default(ansible_facts.lsb.codename) }}

- name: Configure APT repositories in bulk
  ansible.builtin.include_tasks:
    file: add-debian-repo.yml
    apply:
      become: true
  loop: "{{ essential_programs.debian_repos }}"
  loop_control:
    label: "{{ item.id }}"
  vars:
    repo: "{{ item }}"

# Update
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 0
  become: true

# Install
- name: Install custom Debian repository packages
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: present
    install_recommends: true
  loop: "{{ essential_programs.debian_repos }}"
  loop_control:
    label: "{{ item.id }}"
  become: true

###################
##### Flatpak #####
###################
- name: Install Flatpak apps
  community.general.flatpak:
    name: "{{ essential_programs.flatpak }}"
    state: present
    remote: flathub
    method: system
  become: true

###################
# Common Programs #
###################
- name: Install common programs on Debian-based
  ansible.builtin.apt:
    name: "{{ essential_programs.common }}"
    state: present
    install_recommends: false
  become: true
