---

###################
### Custom Repo ###
###################
- name: Determine upstream Ubuntu codename for PPAs
  ansible.builtin.set_fact:
    upstream_codename: >-
      {{ upstream_codename_map[
           (
             ansible_facts['distribution']
               | lower
               | replace(' ', '_')
           ) ~ '_' ~
           ansible_facts.lsb.major_release
         ]
         | default(ansible_facts.lsb.codename) }}

- name: Cleanup any legacy underscore-named repo lists
  become: true
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/{{ item.id }}.list"
    state: absent
  loop: "{{ essential_programs.debian_repos }}"
  loop_control:
    label: "{{ item.id }}"

- name: Configure APT repositories in bulk
  ansible.builtin.include_tasks:
    file: add-debian-repo.yml
    apply:
      become: true
  loop: "{{ essential_programs.debian_repos }}"
  loop_control:
    label: "{{ item.id }}"
  vars:
    repo: "{{ item }}"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 0
  become: true

- name: Install custom Debian repository packages
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: present
    install_recommends: true
  loop: "{{ essential_programs.debian_repos }}"
  loop_control:
    label: "{{ item.id }}"
  become: true

###################
##### Flatpak #####
###################
- name: Install Flatpak apps
  community.general.flatpak:
    name: "{{ essential_programs.flatpak }}"
    state: present
    remote: flathub
    method: system
  become: true

###################
# Common Programs #
###################
- name: Install common programs on Debian-based
  ansible.builtin.apt:
    name: "{{ essential_programs.common }}"
    state: present
    install_recommends: false
  become: true

#######################
## JetBrains Toolbox ##
#######################
# Source: https://github.com/nagygergo/jetbrains-toolbox-install
- name: Fetch JetBrains Toolbox release info
  ansible.builtin.uri:
    url: "https://data.services.jetbrains.com/products/releases?code=TBA&latest=true&type=release"
    return_content: true
  register: jetbrains_toolbox_release

- name: Set JetBrains Toolbox download URL
  ansible.builtin.set_fact:
    jetbrains_toolbox_url: "{{ jetbrains_toolbox_release.json.TBA[0].downloads.linux.link }}"

- name: Determine archive filename from URL
  ansible.builtin.set_fact:
    toolbox_archive_filename: "{{ jetbrains_toolbox_url | basename }}"

- name: Download JetBrains Toolbox archive
  ansible.builtin.get_url:
    url: "{{ jetbrains_toolbox_url }}"
    dest: "/tmp/{{ toolbox_archive_filename }}"
    mode: '0644'

- name: Create JetBrains Toolbox install dir
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/JetBrains/Toolbox"
    state: directory
    mode: '0755'

- name: Extract JetBrains Toolbox
  ansible.builtin.unarchive:
    src: "/tmp/{{ toolbox_archive_filename }}"
    dest: "{{ ansible_env.HOME }}/.local/share/JetBrains/Toolbox"
    remote_src: true
    extra_opts: ['--strip-components=1']

- name: Make toolbox binary executable
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox"
    mode: '0755'

- name: Ensure user local bin directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: '0755'

- name: Symlink jetbrains-toolbox to local bin
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox"
    dest: "{{ ansible_env.HOME }}/.local/bin/jetbrains-toolbox"
    state: link

- name: Clean up downloaded archive
  ansible.builtin.file:
    path: "/tmp/{{ toolbox_archive_filename }}"
    state: absent
