---

###################
### Custom Repo ###
###################
- name: Configure APT repositories in bulk
  become: true
  ansible.builtin.include_tasks:
    file: add-debian-repo.yml
    apply:
      become: true
  loop: "{{ essential_programs.debian_repos }}"
  loop_control:
    label: "{{ item.id }}"
  vars:
    repo: "{{ item }}"

# Update
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 0
  become: true

# Install
- name: Install custom Debian repository packages
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: present
    install_recommends: true
  loop: "{{ essential_programs.debian_repos }}"
  loop_control:
    label: "{{ item.id }}"
  become: true

###################
##### Flatpak #####
###################
- name: Install Flatpak apps
  community.general.flatpak:
    name: "{{ essential_programs.flatpak }}"
    state: present
    remote: flathub
    method: system
  become: true

###################
# Common Programs #
###################
- name: Install common programs on Debian-based
  ansible.builtin.apt:
    name: "{{ essential_programs.common }}"
    state: present
    install_recommends: false
  become: true
