---

#########
# DOCKER #
#########

# STEP 1: Install Prerequisites
- name: Update package index
  ansible.builtin.apt:
    update_cache: true
  become: true

# STEP 2: Add Docker's Official GPG Key
- name: Create keyrings directory
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.gpg
    mode: '0644'
  become: true

- name: Convert Docker GPG key to dearmored format
  ansible.builtin.command:
    cmd: gpg --dearmor -o /usr/share/keyrings/docker.gpg /tmp/docker.gpg
    creates: /usr/share/keyrings/docker.gpg
  become: true

- name: Remove temporary GPG key file
  ansible.builtin.file:
    path: /tmp/docker.gpg
    state: absent
  become: true

# STEP 3: Add Docker Repository
- name: Add Docker repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: >-
      deb [arch=amd64 signed-by=/usr/share/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu {{ docker_ubuntu_codename }} stable
    create: true
    mode: '0644'
  become: true

- name: Update package cache after adding repository
  ansible.builtin.apt:
    update_cache: true
  become: true

# STEP 4: Install Docker
- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
  become: true

# USER CONFIGURATION
- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
  become: true

# DOCKER-COMPOSE INSTALLATION
- name: Get latest docker-compose release version
  ansible.builtin.uri:
    url: https://api.github.com/repos/docker/compose/releases/latest
    method: GET
    return_content: true
  register: docker_compose_release

- name: Download docker-compose binary
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_release.json.tag_name }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  become: true

- name: Verify docker-compose installation
  ansible.builtin.command: docker-compose --version
  register: docker_compose_version
  changed_when: false

- name: Display docker-compose version
  ansible.builtin.debug:
    msg: "Docker Compose installed: {{ docker_compose_version.stdout }}"
