---
- name: Enable date display in panel clock
  ansible.builtin.command:
    cmd: gsettings set org.cinnamon.desktop.interface clock-show-date true
  changed_when: true

- name: Configure date format for Linux Mint
  ansible.builtin.command:
    cmd: gsettings set org.cinnamon.desktop.interface clock-format "%d/%m/%y | %a, %B | %H:%M:%S"
  changed_when: true

- name: Enable 24-hour clock format
  ansible.builtin.command:
    cmd: gsettings set org.cinnamon.desktop.interface clock-use-24h true
  changed_when: true

- name: Show seconds in clock
  ansible.builtin.command:
    cmd: gsettings set org.cinnamon.desktop.interface clock-show-seconds true
  changed_when: true

- name: Configure screenshot shortcut Super+Shift+S
  ansible.builtin.command:
    cmd: gsettings set org.cinnamon.desktop.keybindings.media-keys area-screenshot "['<Super><Shift>s']"
  changed_when: true
