---

- name: Configure screenshot shortcut Super+Shift+S
  ansible.builtin.command:
    cmd: gsettings set org.cinnamon.desktop.keybindings.media-keys area-screenshot "['<Super><Shift>s']"
  changed_when: true
