---
- name: Enable date display in panel clock
  ansible.builtin.command:
    cmd: gsettings set org.cinnamon.desktop.interface clock-show-date true
  changed_when: true

- name: Enable 24-hour clock format
  ansible.builtin.command:
    cmd: gsettings set org.cinnamon.desktop.interface clock-use-24h true
  changed_when: true

- name: Show seconds in clock
  ansible.builtin.command:
    cmd: gsettings set org.cinnamon.desktop.interface clock-show-seconds true
  changed_when: true

- name: Get calendar applet instance ID
  ansible.builtin.shell:
    cmd: gsettings get org.cinnamon enabled-applets | grep -oP 'calendar@cinnamon\.org:\K[0-9]+'
  register: calendar_instance_id
  changed_when: false

- name: Create calendar applet config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.cinnamon/configs/calendar@cinnamon.org"
    state: directory
    mode: '0755'

- name: Configure calendar applet custom date format
  ansible.builtin.copy:
    content: |
      {
          "use-custom-format": {
              "type": "switch",
              "value": true
          },
          "custom-format": {
              "type": "entry",
              "value": "%d/%m/%y | %a, %B | %H:%M:%S"
          },
          "custom-tooltip-format": {
              "type": "entry",
              "value": "%A, %B %e, %H:%M"
          }
      }
    dest: "{{ ansible_env.HOME }}/.cinnamon/configs/calendar@cinnamon.org/{{ calendar_instance_id.stdout }}.json"
    mode: '0644'
  when: calendar_instance_id.stdout != ""

- name: Reload calendar applet
  ansible.builtin.command:
    cmd: dbus-send --type=method_call --dest=org.Cinnamon.LookingGlass /org/Cinnamon/LookingGlass org.Cinnamon.LookingGlass.ReloadExtension string:'calendar@cinnamon.org' string:'APPLET'
  changed_when: true
  when: calendar_instance_id.stdout != ""
  failed_when: false

- name: Configure screenshot shortcut Super+Shift+S
  ansible.builtin.command:
    cmd: gsettings set org.cinnamon.desktop.keybindings.media-keys area-screenshot "['<Super><Shift>s']"
  changed_when: true
