---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
  become: true
